name: Release

on:
  workflow_dispatch:

jobs:

  build:      
    uses: AvaloniaUI/build-common/.github/workflows/library-cicd.yml@main
    with:
      runs_on: windows-latest
      install_workloads: "android ios"
      dotnet_sdk: 10.0.300
      validate_release_branch: true
      artifact_name: packages
      push_package: 'false'

  # We don't push via library-cicd.yml, because it's not possible to pass environment with environment-specific secrets.
  push:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: ./nupkgs
      - name: Avalonia release
        run: dotnet nuget push './nupkgs/Avalonia.Controls.WebView.*.nupkg' --api-key '${{ secrets.RELEASE_MANAGER_API_KEY }}' --source '${{vars.RELEASE_MANAGER_UPLOAD_URL}}'
      - name: XPF release
        run: dotnet nuget push './nupkgs/Avalonia.Xpf.Controls.WebView.*.nupkg' --api-key '${{ secrets.RELEASE_MANAGER_API_KEY }}' --source '${{vars.RELEASE_MANAGER_UPLOAD_URL_XPF}}'
